import Foundation

/// Hands an attention item to a coding agent ("harness") running in a terminal, inside a dedicated
/// git worktree for the PR, so several PRs can be worked on in parallel without touching the main checkout.
public struct HandoffPlan: Sendable, Equatable {
    public var repo: RepoRef
    public var prNumber: Int
    public var branch: String
    /// The main local clone of the repo.
    public var checkout: String
    /// `<checkout parent>/<checkout name>-pr-<N>`, matching sibling worktrees like `remote-flows-release-prep`.
    public var worktree: String
    public var promptFile: String
    /// Shell command template; `{prompt_file}` is replaced with the prompt file path.
    public var harnessCommand: String

    public init(
        repo: RepoRef, prNumber: Int, branch: String, checkout: String, promptFile: String, harnessCommand: String
    ) {
        self.repo = repo
        self.prNumber = prNumber
        self.branch = branch
        self.checkout = checkout
        self.worktree = Handoff.worktreePath(checkout: checkout, pr: prNumber)
        self.promptFile = promptFile
        self.harnessCommand = harnessCommand
    }
}

public enum Handoff {
    public static let defaultHarnessCommand = #"claude "$(cat {prompt_file})""#

    public static func worktreePath(checkout: String, pr: Int) -> String {
        let url = URL(fileURLWithPath: checkout).standardizedFileURL
        return url.deletingLastPathComponent().appendingPathComponent("\(url.lastPathComponent)-pr-\(pr)").path
    }

    /// POSIX single-quoting: safe for any path or branch name.
    public static func shellQuote(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: #"'\''"#) + "'"
    }

    /// A zsh script run in the terminal. Interactive login shell (`-il`) so .zshrc functions such as a
    /// `claude` wrapper are available. Every step echoes what it does, and the shell stays open at the end.
    public static func script(_ p: HandoffPlan) -> String {
        let harness = p.harnessCommand.replacingOccurrences(of: "{prompt_file}", with: #""$PROMPT_FILE""#)
        return """
            #!/bin/zsh -il
            # Generated by Triage: \(p.repo.fullName) #\(p.prNumber)
            CHECKOUT=\(shellQuote(p.checkout))
            WT=\(shellQuote(p.worktree))
            BRANCH=\(shellQuote(p.branch))
            PROMPT_FILE=\(shellQuote(p.promptFile))

            fail() { echo "✗ $1"; exec zsh -il; }

            cd "$CHECKOUT" || fail "checkout not found: $CHECKOUT"
            if [ ! -d "$WT" ]; then
              existing=$(git worktree list --porcelain |
                awk -v b="branch refs/heads/$BRANCH" '/^worktree /{p=substr($0,10)} $0==b{print p}')
              if [ -n "$existing" ]; then
                echo "→ $BRANCH is already checked out at $existing, using that"
                WT="$existing"
              elif git fetch --quiet origin "$BRANCH" 2>/dev/null; then
                echo "→ creating worktree $WT on $BRANCH"
                git worktree add --quiet "$WT" "$BRANCH" || fail "couldn't create the worktree"
              else
                echo "→ $BRANCH isn't on origin (fork?), checking out with gh"
                git worktree add --quiet --detach "$WT" && (cd "$WT" && gh pr checkout \(p.prNumber)) ||
                  fail "couldn't check out PR #\(p.prNumber)"
              fi
            fi

            cd "$WT" || fail "worktree missing: $WT"
            git pull --ff-only --quiet 2>/dev/null || echo "! couldn't fast-forward; using the local state"
            echo "→ \(p.repo.fullName) #\(p.prNumber) in $PWD"
            \(harness)
            exec zsh -il

            """
    }

    /// Finds a local clone of `repo` by looking for `<root>/<name>` whose origin points at it.
    public static func findCheckout(_ repo: RepoRef, roots: [String]) -> String? {
        for root in roots {
            let path = (root as NSString).appendingPathComponent(repo.name)
            guard FileManager.default.fileExists(atPath: (path as NSString).appendingPathComponent(".git")),
                let origin = git(["-C", path, "remote", "get-url", "origin"]),
                originMatches(origin, repo)
            else { continue }
            return path
        }
        return nil
    }

    public static func originMatches(_ origin: String, _ repo: RepoRef) -> Bool {
        let o = origin.lowercased().replacingOccurrences(of: ".git", with: "")
        return o.hasSuffix(":" + repo.fullName.lowercased()) || o.hasSuffix("/" + repo.fullName.lowercased())
    }

    static func git(_ args: [String]) -> String? {
        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        p.arguments = args
        let out = Pipe()
        p.standardOutput = out
        p.standardError = Pipe()
        guard (try? p.run()) != nil else { return nil }
        p.waitUntilExit()
        guard p.terminationStatus == 0 else { return nil }
        return String(decoding: out.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
