import Testing

@testable import TriageCore

/// Danger's comment as GitLab returns it.
private let danger = """
    <!--
      0 failure:
      1 warning:  ⚠️ Changes detect...


      DangerID: danger-id-Danger;
    -->


    <table>
      <thead>
        <tr>
          <th width="50"></th>
          <th width="100%" data-danger-table="true">Warnings</th>
        </tr>
      </thead>
      <tbody><tr>
          <td>:warning:</td>
          <td>

      ⚠️ Changes detected in `apps/employ/src/constants/dashboardRoutePermissions.ts`. Please remember to also \
    update the product access mapping in the [documentation](https://example.com/docs) if applicable.
      </td>
        </tr>
      </tbody>
    </table>



    <p align="right">
      Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 758bcd7690951d72a41effd99e3b6a3386f8673c
    </p>
    """

@Test func dangersHTMLBecomesReadableMarkdown() {
    #expect(
        CommentText.readable(danger) == """
            ⚠️

            ⚠️ Changes detected in `apps/employ/src/constants/dashboardRoutePermissions.ts`. Please remember to \
            also update the product access mapping in the [documentation](https://example.com/docs) if applicable.

            Generated by 🚫 [dangerJS](https://danger.systems/js) against 758bcd7690951d72a41effd99e3b6a3386f8673c
            """)
}

@Test func theFindingTitleSkipsHiddenMetadata() {
    #expect(
        Classifier.findingTitle(danger)
            == "⚠️ Changes detected in apps/employ/src/constants/dashboardRoutePermissions.ts. Please remem")
    #expect(Classifier.findingTitle("See **[the docs](https://x.dev)** for `make`") == "See the docs for make")
}

@Test func inlineHTMLBecomesMarkdown() {
    let html = "Use <code>make</code>, <b>not</b> <em>npm</em>.<br>See <a href='https://x.dev/a?b=1&amp;c=2'>docs</a>"
    #expect(CommentText.readable(html) == "Use `make`, **not** *npm*.\nSee [docs](https://x.dev/a?b=1&c=2)")
}

@Test func listsAndEntities() {
    #expect(
        CommentText.readable("<ul><li>a &amp; b</li><li>&lt;div&gt; &#x1F680; &#39;x&#39;</li></ul>")
            == "• a & b\n• <div> 🚀 'x'")
}

@Test func codeAndGenericsAreLeftAlone() {
    let text = "Returns `Array<Int>` from <T> helpers:\n```html\n<table><tr><td>x</td></tr></table>\n```"
    #expect(CommentText.readable(text) == text)
}

@Test func plainMarkdownIsUnchanged() {
    let md = "### Bug: off by one\n\n**High Severity**\n\nThe loop at 10:30:45 skips `items[0]`. :unknown_code:"
    #expect(CommentText.readable(md) == md)
}
